<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Produk_retail_mutasi_model extends CI_Model
{

    public $table = 'produk_retail_mutasi';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('a.id,a.id_toko,a.id_users,a.tgl,a.id_produk,a.id_users_asal,a.id_users_tujuan,a.keterangan,b.barcode,b.nama_produk, c.first_name AS first_name_asal, c.last_name AS last_name_asal, d.first_name AS first_name_tujuan, d.last_name AS last_name_tujuan');
        $this->datatables->from('produk_retail_mutasi a');
        $this->datatables->join('produk_retail b', 'a.id_produk=b.id_produk_2 AND a.id_toko=b.id_toko');
        $this->datatables->join('users c', 'a.id_users_asal=c.id_users AND a.id_toko=c.id_toko');
        $this->datatables->join('users d', 'a.id_users_tujuan=d.id_users AND a.id_toko=d.id_toko');
        /**
         * anchor(site_url('admin/produk_retail_mutasi/update/$1'), '<button class="btn btn-xs btn-info"><i class="ace-icon fa fa-pencil bigger-120"></i></button>') . "&nbsp;&nbsp;" . 
         */
        $this->datatables->add_column('action', anchor(site_url('admin/produk_retail_mutasi/delete/$1'), '<button class="btn btn-xs btn-danger"><i class="ace-icon fa fa-trash bigger-120"></i></button>', 'onclick="javasciprt: return confirm(\'Batalkan mutasi stok ini ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('id_toko', $q);
        $this->db->or_like('id_users', $q);
        $this->db->or_like('tgl', $q);
        $this->db->or_like('id_users_asal', $q);
        $this->db->or_like('id_users_tujuan', $q);
        $this->db->or_like('keterangan', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('id_toko', $q);
        $this->db->or_like('id_users', $q);
        $this->db->or_like('tgl', $q);
        $this->db->or_like('id_users_asal', $q);
        $this->db->or_like('id_users_tujuan', $q);
        $this->db->or_like('keterangan', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Produk_retail_mutasi_model.php */
/* Location: ./application/models/Produk_retail_mutasi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-03-06 05:31:50 */
/* http://harviacode.com */
