<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tukarphone_model extends CI_Model
{

    public $table = 'tukarphone';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('id,id_toko,id_users,tgl,id_sales,id_orders,id_pembelian,nama_penukar,alamat_penukar,no_hp_penukar');
        $this->datatables->from('tukarphone');
        $this->datatables->add_column('action', anchor(site_url('admin/tukarphone/read'), '<button class="btn btn-xs btn-success">Penjualan</button>') . "&nbsp;&nbsp;&nbsp;&nbsp;" . anchor(site_url('admin/tukarphone/update'), '<button class="btn btn-xs btn-info">Pembelian</button>'), 'id');
        return $this->datatables->generate();
    }
}

/* End of file Toko_model.php */
/* Location: ./application/models/Toko_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-31 09:19:41 */
/* http://harviacode.com */
